"""One command, every table and figure, all from the per-attempt log.

    python -m src.make_tables_v3 runs/x/attempts_v3.jsonl --outdir tables/

The Open Science section claims "no number is transcribed by hand, and re-running
the script reproduces them exactly". That claim is currently false: two of the
three figure scripts hard-code every rate and one has no log-reading path at all.
This module makes the claim true. Run it twice and the outputs are byte
identical; if a number is not in the log it does not appear in a table.

Emits, with one declared interval method throughout:
  tab_power.tex         what a measured floor permits (Prop. power)
  tab_main.tex          per-model rates, with n_persons/n_targets/n_attempts
  tab_spectrum.tex      the probe spectrum, with n and an interval per row
  tab_perfield.tex      every rate split by field
  tab_2x2.tex           the four cells, placebo contrast and DiD
  tab_feasibility.tex   the operating-point feasibility table
  fig_capacity.pdf      the measured operating characteristic
  numbers.json          every scalar the prose quotes, keyed by name
"""
from __future__ import annotations

import argparse
import json
import math
import os
from typing import Dict, List, Optional

import numpy as np

from .diagnostics import (acr_on_controls, copy_diagnostic, feasibility,
                          per_field, seed_variance, two_by_two)
from .logschema import load, validate
from .stats_v3 import (cluster_bootstrap_rate, mcnemar, min_detectable_m,
                       paired_bootstrap_diff, power_n, recall_fraction)

INTERVAL_NOTE = ("All intervals are 95\\% person-clustered bootstrap, paired "
                 "across arms where the design is matched; boundary cells use a "
                 "person-level Clopper--Pearson bound, which is stated rather "
                 "than an unexplained effective sample size.")


def _u(g, by="person_id"):
    return [list(v["exact_match"].astype(int)) for _, v in g.groupby(by)]


def _units_map(g, by="person_id"):
    return {pid: list(v["exact_match"].astype(int)) for pid, v in g.groupby(by)}


def _pct(x, d=1):
    return "--" if x is None or not np.isfinite(x) else f"{100*x:.{d}f}"


def _tex_table(caption: str, label: str, header: List[str], rows: List[List[str]],
               colspec: Optional[str] = None, note: str = "") -> str:
    colspec = colspec or ("l" + "c" * (len(header) - 1))
    body = "\n".join(" & ".join(r) + " \\\\" for r in rows)
    return (f"% generated by src.make_tables_v3 -- do not edit by hand\n"
            f"\\begin{{table}}[t]\n\\centering\n\\caption{{{caption} {note}}}\n"
            f"\\label{{{label}}}\n\\footnotesize\n"
            f"\\setlength{{\\tabcolsep}}{{4pt}}\n"
            f"\\begin{{tabular}}{{@{{}}{colspec}@{{}}}}\n\\toprule\n"
            + " & ".join(header) + " \\\\\n\\midrule\n" + body
            + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# --------------------------------------------------------------------------- #
def table_power(df, numbers: Dict) -> str:
    sweep = df[(df["capacity_k"] > 0) & (df["model_state"] == "finetuned")]
    rows, header = [], ["", ]
    picks = []
    for k in sorted(sweep["capacity_k"].unique()):
        c = sweep[(sweep["capacity_k"] == k) &
                  (sweep["target_membership"] == "control")]
        if len(c):
            picks.append((int(k), float(c["exact_match"].mean()), int(len(c))))
    # keep a readable subset spanning the range
    chosen = [p for p in picks if p[0] in (6, 8, 20, 64)] or picks[:4]
    header = [""] + [f"$k{{=}}{k}$" for k, _, _ in chosen]
    r_alpha = ["Control rate $\\alpha_k$"]
    r_ceil = ["Advantage ceiling $1-\\alpha_k$"]
    r_mdm = ["$m^\\ast$ at $n$ run"]
    r_n = ["$n$ per arm for $m=0.10$"]
    for k, a, n in chosen:
        r_alpha.append(f"{a:.2f}")
        r_ceil.append(f"{1-a:.2f}")
        r_mdm.append(f"{min_detectable_m(a, n):.2f}")
        r_n.append(f"{power_n(a, 0.10):.0f}")
        numbers[f"alpha_k{k}"] = a
        numbers[f"min_detectable_m_k{k}"] = min_detectable_m(a, n)
        numbers[f"n_for_m010_k{k}"] = power_n(a, 0.10)
    return _tex_table(
        "What a measured floor permits, from Eq.~\\ref{eq:power} at two-sided "
        "$5\\%$ and $80\\%$ power. $m^\\ast$ is the smallest recall fraction "
        "detectable with the attempts per arm actually run.",
        "tab:power", header, [r_alpha, r_ceil, r_mdm, r_n])


def table_main(df, numbers: Dict) -> str:
    rows = []
    for model, g in df[df["model_state"] == "finetuned"].groupby("model_name"):
        t = g[g["target_membership"] == "trained"]
        c = g[g["target_membership"] == "control"]
        if not len(t) or not len(c):
            continue
        et = cluster_bootstrap_rate(_u(t))
        ec = cluster_bootstrap_rate(_u(c))
        ed = paired_bootstrap_diff(_units_map(t), _units_map(c))
        m = recall_fraction(et.point, ec.point)
        n_pers = t["person_id"].nunique()
        n_tgt = t.groupby(["person_id", "field"]).ngroups
        rows.append([
            model.replace("_", "\\_"), str(n_pers), str(n_tgt), str(len(t)),
            f"{_pct(et.point)} [{_pct(et.lo)}, {_pct(et.hi)}]",
            f"{_pct(ec.point)} [{_pct(ec.lo)}, {_pct(ec.hi)}]",
            f"{_pct(ed.point)} [{_pct(ed.lo)}, {_pct(ed.hi)}]",
            f"{m:.2f}" if np.isfinite(m) else "--",
        ])
        numbers[f"{model}_pi"] = et.point
        numbers[f"{model}_alpha"] = ec.point
        numbers[f"{model}_tau"] = ed.point
        numbers[f"{model}_recall_fraction"] = m
    return _tex_table(
        "Per-model audit. $n$ is reported three ways because the unit of "
        "analysis governs every interval: persons, (person, field) targets, and "
        "attempts.",
        "tab:main",
        ["Model", "persons", "targets", "attempts", "$\\pi_k$ [95\\% CI]",
         "$\\alpha_k$ [95\\% CI]", "$\\hat\\tau$ [95\\% CI]", "$m$"],
        rows, colspec="lcccccc c", note=INTERVAL_NOTE)


def table_spectrum(df, numbers: Dict) -> str:
    order = ["fixed", "piiscope", "piicompass", "random_restart", "gcg_fluent",
             "gcg_free", "gcg_anchored", "softprompt"]
    pretty = {"fixed": "Fixed prompt", "piiscope": "PII-Scope",
              "piicompass": "Compass-inspired", "random_restart": "Random restart",
              "gcg_fluent": "GCG, fluency-reg.", "gcg_free": "GCG, context-free",
              "gcg_anchored": "GCG, identifier-anchored",
              "softprompt": "Soft prompt (ceiling)"}
    rows = []
    for probe in order:
        g = df[(df["probe"] == probe) & (df["model_state"] == "finetuned")]
        if not len(g):
            continue
        t = g[g["target_membership"] == "trained"]
        c = g[g["target_membership"] == "control"]
        if not len(t) or not len(c):
            continue
        et, ec = cluster_bootstrap_rate(_u(t)), cluster_bootstrap_rate(_u(c))
        ed = paired_bootstrap_diff(_units_map(t), _units_map(c))
        m = recall_fraction(et.point, ec.point)
        rows.append([
            pretty.get(probe, probe), str(t.groupby(["person_id", "field"]).ngroups),
            f"{int(t['forward_passes'].median()):,}".replace(",", "\\,")
            if "forward_passes" in t else "--",
            f"{_pct(et.point)}", f"{_pct(ec.point)}",
            f"{_pct(ed.point)} [{_pct(ed.lo)}, {_pct(ed.hi)}]",
            f"{m:.2f}" if np.isfinite(m) else "--",
        ])
        numbers[f"spectrum_{probe}_pi"] = et.point
        numbers[f"spectrum_{probe}_alpha"] = ec.point
    return _tex_table(
        "Probe spectrum. The forward-pass column is what makes the comparison "
        "budget-matched rather than nominal; a soft prompt that saturates both "
        "arms is a ceiling effect and its zero difference is uninformative.",
        "tab:spectrum",
        ["Probe", "targets", "fwd passes", "$\\pi_k$", "$\\alpha_k$",
         "$\\hat\\tau$ [95\\% CI]", "$m$"], rows, note=INTERVAL_NOTE)


def table_perfield(df, numbers: Dict, h_inf: Dict[str, float]) -> str:
    res = per_field(df[df["model_state"] == "finetuned"], h_inf)
    rows = []
    for r in sorted(res["rows"], key=lambda x: (x["field"], x["capacity_k"])):
        if r["capacity_k"] not in (6, 20, 64):
            continue
        rows.append([r["field"], str(int(r["capacity_k"])),
                     f"{r['h_inf_bits']:.1f}" if r["h_inf_bits"] else "--",
                     f"{_pct(r['pi'])}", f"{_pct(r['alpha'])}",
                     f"{r['recall_fraction']:.2f}"
                     if np.isfinite(r["recall_fraction"]) else "--"])
        numbers[f"perfield_{r['field']}_k{int(r['capacity_k'])}_alpha"] = r["alpha"]
    return _tex_table(
        "Rates split by field. A curve pooling fields of different min-entropy "
        "cannot be read under any single-parameter capacity model.",
        "tab:perfield",
        ["Field", "$k$", "$H_\\infty$", "$\\pi_k$", "$\\alpha_k$", "$m$"], rows)


def table_2x2(df, numbers: Dict, k: int = 20) -> str:
    t = two_by_two(df, capacity_k=k)
    if "did" not in t:
        return "% 2x2 table omitted: the log has no base-model arm\n"
    r = t["rates"]
    rows = [
        ["Fine-tuned", _pct(r["finetuned_trained"]), _pct(r["finetuned_control"]),
         _pct(t["tau_rec"])],
        ["Original", _pct(r["base_trained"]), _pct(r["base_control"]),
         _pct(t["placebo_b_base"])],
    ]
    for key in ("tau_rec", "tau_mod", "placebo_b_base", "did"):
        numbers[f"twobytwo_{key}"] = t[key]
    note = (f"The placebo contrast on the original checkpoint is "
            f"${_pct(t['placebo_b_base'])}$ points and is the design's only "
            f"testable implication; the difference-in-differences is "
            f"${_pct(t['did'])}$ points. " + INTERVAL_NOTE)
    return _tex_table(
        f"The $2{{\\times}}2$ at $k{{=}}{k}$.", "tab:base-control",
        ["Checkpoint", "D success", "C success", "D$-$C"], rows, note=note)


def table_feasibility(df, numbers: Dict, tolerance: float = 0.01) -> str:
    res = feasibility(df[df["model_state"] == "finetuned"], tolerance)
    rows = []
    for r in res["rows"]:
        rows.append([str(int(r["capacity_k"])),
                     _pct(r["alpha"]), _pct(r["alpha_upper_person"]),
                     "yes" if r["clears_tolerance"] else "no",
                     _pct(r["pi"]),
                     f"{r['min_detectable_m']:.2f}"
                     if np.isfinite(r["min_detectable_m"]) else "--",
                     f"{r['n_needed_for_m_target']:.0f}"
                     if np.isfinite(r["n_needed_for_m_target"]) else "--"])
    numbers["feasible_capacities"] = res["feasible_capacities"]
    note = ("The feasible set is the intersection of a certified floor and a "
            "powered instrument. " +
            ("It is empty in this study, which is a result about "
             "optimization-based audits rather than a gap in the study."
             if not res["feasible_capacities"] else ""))
    return _tex_table(
        f"Operating-point feasibility at tolerance ${100*tolerance:.0f}\\%$.",
        "tab:feasibility",
        ["$k$", "$\\alpha_k$", "upper", f"clears", "$\\pi_k$", "$m^\\ast$",
         "$n$ for $m{=}0.1$"], rows, note=note)


def figure_capacity(df, outdir: str, numbers: Dict) -> Optional[str]:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"[tables] matplotlib unavailable ({exc}); skipping the figure")
        return None
    sweep = df[(df["capacity_k"] > 0) & (df["model_state"] == "finetuned")]
    ks, a, p, alo, ahi, plo, phi = [], [], [], [], [], [], []
    for k in sorted(sweep["capacity_k"].unique()):
        g = sweep[sweep["capacity_k"] == k]
        c = g[g["target_membership"] == "control"]
        t = g[g["target_membership"] == "trained"]
        if not len(c) or not len(t):
            continue
        ec, et = cluster_bootstrap_rate(_u(c), 2000), cluster_bootstrap_rate(_u(t), 2000)
        ks.append(k); a.append(ec.point); p.append(et.point)
        alo.append(ec.lo); ahi.append(ec.hi); plo.append(et.lo); phi.append(et.hi)
    if not ks:
        return None
    fig, ax = plt.subplots(figsize=(4.2, 2.8))
    ax.fill_between(ks, 100*np.array(alo), 100*np.array(ahi), alpha=.18, color="#1F6FB2")
    ax.fill_between(ks, 100*np.array(plo), 100*np.array(phi), alpha=.18, color="#B03A2E")
    ax.plot(ks, 100*np.array(a), "o-", ms=3, lw=1.3, color="#1F6FB2",
            label=r"control $\alpha_k$")
    ax.plot(ks, 100*np.array(p), "s-", ms=3, lw=1.3, color="#B03A2E",
            label=r"trained $\pi_k$")
    ax.set_xscale("log", base=2)
    ax.set_xlabel("free prompt tokens $k$")
    ax.set_ylabel("exact-match rate (\\%)" if False else "exact-match rate (%)")
    ax.set_ylim(-3, 103)
    ax.legend(frameon=False, fontsize=8)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(pad=0.3)
    path = os.path.join(outdir, "fig_capacity_measured")
    for ext in ("pdf", "png"):
        fig.savefig(f"{path}.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)
    numbers["sweep_capacities"] = [int(x) for x in ks]
    numbers["sweep_alpha"] = a
    numbers["sweep_pi"] = p
    return path + ".pdf"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("log")
    ap.add_argument("--outdir", default="tables")
    ap.add_argument("--k-2x2", type=int, default=20)
    ap.add_argument("--tolerance", type=float, default=0.01)
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)

    df = load(a.log)
    rep = validate(df, strict=True)
    for w in rep["warnings"]:
        print("warn :", w)

    from .theory import email_min_entropy_en_us, ssn_min_entropy_en_us
    h = {}
    try:
        h = {"ssn": ssn_min_entropy_en_us().h_inf_bits,
             "email": email_min_entropy_en_us().h_inf_bits}
    except Exception:
        pass

    numbers: Dict[str, object] = {"_source_log": os.path.abspath(a.log),
                                  "_n_rows": int(len(df))}
    artefacts = {
        "tab_power.tex": table_power(df, numbers),
        "tab_main.tex": table_main(df, numbers),
        "tab_spectrum.tex": table_spectrum(df, numbers),
        "tab_perfield.tex": table_perfield(df, numbers, h),
        "tab_2x2.tex": table_2x2(df, numbers, a.k_2x2),
        "tab_feasibility.tex": table_feasibility(df, numbers, a.tolerance),
    }
    for name, tex in artefacts.items():
        with open(os.path.join(a.outdir, name), "w") as f:
            f.write(tex)
        print(f"[tables] wrote {os.path.join(a.outdir, name)}")

    fig = figure_capacity(df, a.outdir, numbers)
    if fig:
        print(f"[tables] wrote {fig}")

    # Diagnostics that belong in the prose rather than a table.
    sweep = df[df["capacity_k"] > 0]
    cd = copy_diagnostic(sweep)
    if "overall" in cd and cd["overall"]:
        numbers["copy_full_rate"] = cd["overall"].get("full_copy_rate")
        numbers["copy_verdict"] = cd.get("verdict")
    acr = acr_on_controls(sweep)
    if "rows" in acr:
        for r in acr["rows"]:
            numbers[f"acr_ge1_{r['arm']}"] = r["rate_of_all_targets"]

    with open(os.path.join(a.outdir, "numbers.json"), "w") as f:
        json.dump(numbers, f, indent=2, default=str)
    print(f"[tables] wrote {os.path.join(a.outdir, 'numbers.json')} "
          f"({len(numbers)} scalars)")
    print("\n[tables] every number in the paper should be \\input from here or "
          "read from numbers.json. Re-running reproduces them exactly.")


if __name__ == "__main__":
    main()
